$ANSIBLE_VAULT;1.1;AES256
62393631616534336464633061336661386361396633396261316238393434313966383539363965
3863343332303063383264343963643764313236316139340a343235336538623535623136386638
35623261383763333664373861616233376531376362626231343137336636313935663934376461
3233646639356332320a393662626164313531623835356365346333613831643236383031613631
35663034356564356131306563306239646430623364393239363164613633363561626261646461
31356438346161383962383037653366316530323331626431356461343134656233383032386333
33656266343865636136613066383438383336343233633831323136343231663332383930353433
64643830653631353530
