$ANSIBLE_VAULT;1.1;AES256
36323538643035323932316539363737313833363661653164653231616138393261316230643035
3134376661646638623737343230633465356639623433390a383130646361643562356261303965
32363938383039636635353861303832383834623730373763343431373732646632333461336565
6639356539326466360a306465363735666332613561346263363134343335336365366466363835
33363965616335386364356363346639633933366563303939303834646231326562303638366364
63646530613733663066663037386264383837376666373839626130343930303764646662393933
63323338656262633936626337316139383339373766636262343764653032626435353535323131
62303366373662623863303338353161363033386134626434376263643464636636303766363030
3534
