$ANSIBLE_VAULT;1.1;AES256
66326262393762313131363662333339643737386439613964363566366364346334383962366136
3661666463623435313330643831343465313536373766340a393937633733646234626438636134
38393365663932386564646262376533373937303534346331366366666263366334383566323735
6664316263373132620a636161386337656434353337306663333933656461303864346439326239
34396636643361323837616161363764313035376231616661616531346264366331656533613638
64646633353636383238656332356332356132663432326364396339323133393734656263623864
32306432323162663339323661383330343866343963393261613232383463323039303930633862
31396531323563663761653138653537343432356237383264626366373636383434396564363065
6539
