---
- name: nvidia install
  include_tasks: nvidia_install.yml

- name: nvidia initramfs mudules
  include_tasks: nvidia_initramfs.yml
  
- name: nvidia container toolkit
  include_tasks: nvidia_container_toolkit.yml

- name: nvidia grub
  include_tasks: nvidia_grub.yml

- name: nvidia extra packages
  include_tasks: nvidia_extras.yml

