# - name: wgdashboard linuxvm
#   include_tasks: "{{ playbook_dir }}/roles/portainer_deploys/tasks/generate_and_deploy_compose.yml"
#   vars:
#     compose_name: "wgdashboard"
#     endpoint_id: "{{ hostvars['linuxvm']['portainer_endpoint_id'] }}"
#     reverseproxynetwork: "nginxproxymanager"
