$ANSIBLE_VAULT;1.1;AES256
31306231663266323134616361343161653232373738613836616561366139643038666438633237
6239663262343866613661343661623030663333366639370a613064396432623639666464316563
65386233376632366464363336363231353038643734353061383162343665343939626338313439
3063363835333063330a383839363234663732343035303133306234623631373236346266393963
66626132326661633632366634646134373631363030316334373937663238333030353762323666
35613563633130633431383261663431373965353362336434383634346531303566336435636536
63396234316634326162316566303531346164346534643736356364363530326562326336393764
64643331616635366562333465353634643739333164376434373966626238356439363966656337
39396536303535643963663562303538336130623566333634666462653564643330
