---
- name: Install cli apps on apt (debian 13)
  package:
    name:
      - git
      - sudo
      - nano
      - build-essential
      - cmake
      - make
      - rsync
      - curl
      - tmux
    state: present
  become: true
...