---
- name: Prepare apt to installs
  include_role:
    name: common
    tasks_from:  apt_prepare.yml

- name: Include common cli apps for lxc
  include_tasks: install_cli_apps.yml

- name: neovim
  include_role:
    name: common
    tasks_from: neovim
