---
- name: Install cli apps on apt
  package:
    name:
      - htop
      - btop
      - git
      - nano
      - zsh
      - intel-microcode
      - amd64-microcode
      - unzip
      - stow
      - tree
      - btrfs-progs
      - zram-tools
      - build-essential
      - cmake
      - imagemagick
      - ffmpeg
      - gamemode
      - gvfs
      - gvfs-backends
      - firmware-linux
      - python3-btrfsutil
      - gawk 
      - inotify-tools
      - make
      - ntfs-3g
      - tmux
      - python3-launchpadlib
      - yt-dlp 
      - smartmontools
      - hdparm
      - libarchive-zip-perl # for crc32 hex
      - duf
      - ncdu
      - wpasupplicant
      - wireless-tools
      - isc-dhcp-client
    state: present
  become: true
...